### ISSUE TITLE
Замечания по 7.1

### ISSUE THREAD

**Issue by sergey-shambir** [irina-yambatrova/labs#1]
- вместо `Vector2f(&coordinatePoints)[AMOUNT_POINTS]` следует использовать `std::vector<Vector2f> const& points`
- название функции CoordPoints не говорит о её предназначении, следует переименовать, чтобы стало понятно, какие координаты она вычисляет. Кроме того, название функции должно начинаться с глагола (напр. calculate)
- могу ошибаться, но по-моему вместо `watch.point.setPosition(coordinatePoints[i].x, coordinatePoints[i].y);` можно написать `watch.point.setPosition(coordinatePoints[i]);`
- нужно сделать отдельную функцию рисования часов, которая выполняет всё рисование, за исключением очистки окна и `window.display()`.
- `ContextSettings settings;` должны передаваться в конструктор RenderWindow, а не просто устанавливаться.

**Comment by irina-yambatrova** [comment]
исправила,кроме 1 пункта

**Comment by sergey-shambir** [comment]
Где объявлен массив coordinatePoints?

**Comment by irina-yambatrova** [comment]
исправила

**Comment by sergey-shambir** [comment]
Принято
