### ISSUE TITLE
Замечания по 1.3

### ISSUE THREAD

**Issue by sergey-shambir** [irina-yambatrova/labs#2]
- названия main_Dir, main_Url, correct_Url не соответствуют соглашению PEP8, букв верхнего регистра быть не должно
- названия maxLenUrlsList, numbPages, urlsList, savedPages не соответствуют соглашению PEP8
- название переменной list1 ни о чём не говорит
- название переменной list2 ни о чём не говорит
- названия переменных i, j, k ни о чём не говорят
- в функции Save_Recources_Url следует выделить подфункцию, как минимум, для преобразования имени файла

**Comment by irina-yambatrova** [comment]
исправила

**Comment by sergey-shambir** [comment]
Принято
